### PR TITLE
Bugfix double realtime connections

### PR DESCRIPTION
**Pull request by s3ppo**
https://github.com/appwrite/sdk-for-flutter/issues/41

### CODE REVIEW

**Review by lohanidamodar — APPROVED** [review]

**Comment by lohanidamodar** [comment]
@s3ppo Thank you so much for the contribution.

**Comment by christyjacob4** [comment]
@s3ppo Thank you so much for your contribution
 please raise a PR to the `sdk-generator` repo which is where we generate this SDK from 😃

**Comment by s3ppo** [comment]
sorry didnt know that.. i made a PR in the sdk-generator ;-)

**Comment by s3ppo** [comment]
@christyjacob4 possible to get that merged? i always have to fix that manual after i pull from pub.dev ;)

**Pull request closed without merging**
